files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /pyxoverloaded/src/main/res/values/strings.xml
    translation: /pyxoverloaded/src/main/res/values-%android_code%/strings.xml
